# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', timeFormat: false, dateFormat: 'YYYY-MM-DD' }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Pin to Top", name: "pin", widget: "boolean", default: false, required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Star Mark", name: "starMark", widget: "boolean", default: false, required: false}
      - { label: "Comment", name: "comment", widget: "boolean", default: true, required: false}
