# config.yml

backend:
  name: github
  repo: Lei1025/lei1025.github.io
  branch: master # Branch to update (optional; defaults to master)
  preview_context: my-provider/deployment
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }


